### ISSUE TITLE
`ChainSync` requesting the same block multiple times

### ISSUE THREAD

**Issue by altonen** [paritytech/polkadot-sdk#1915]
While running a burn-in for #1631, the logs showed that multiple different peers were banned because they had made the same block request more than once: https://github.com/paritytech/polkadot-sdk/blob/a1171e6e81d5c103e36d40c0a50d2e37157c3dcc/substrate/client/network/sync/src/block_request_handler.rs#L65

This bug is likely in master since the libp2p upgrade doesn't change any syncing-related logic

**Comment by altonen** [comment]
Reported by @dmitry-markin: this has been happening at least on Kusama (likely Polkadot too) already a month ago.

**Comment by dmitry-markin** [comment]
The same warning was happening in Subspace back on 2023-08-09, reported here: https://github.com/paritytech/polkadot-sdk/issues/493#issuecomment-1691854689

**Comment by nazar-pc** [comment]
Could be https://github.com/subspace/subspace/issues/2122 caused by https://github.com/paritytech/polkadot-sdk/pull/1812

**Comment by dmitry-markin** [comment]
> Could be [subspace/subspace#2122](https://github.com/subspace/subspace/issues/2122) caused by #1812

May be https://github.com/paritytech/polkadot-sdk/pull/1812 introduced another issue, but this issue was already happening way before https://github.com/paritytech/polkadot-sdk/pull/1812 was merged.

**Comment by nazar-pc** [comment]
Yes, our conclusion is that there are several issues, but #1812 seems to trigger some other more often that before.

**Comment by dmitry-markin** [comment]
So far, there are at least 4 issues in `ChainSync`:

1. `BlockCollection`: blocks below the common number are requested from peers: [logs](https://gist.github.com/dmitry-markin/d4a9a76468d35efa9883e92b27f71bbd#file-gistfile1-txt-L72). Addressed by https://github.com/paritytech/polkadot-sdk/pull/2045.
2. When we queue blocks, we update all peers’ common numbers (see [`on_block_queued()`](https://github.com/paritytech/polkadot-sdk/blob/8ce16ee6ff190912995dc6c8da85b741eaada395/substrate/client/network/sync/src/lib.rs#L1270-L1271)), but when we import blocks, we only update the common number of the peer that was the origin of the blocks (see [`on_blocks_processed()`](https://github.com/paritytech/polkadot-sdk/blob/8ce16ee6ff190912995dc6c8da85b741eaada395/substrate/client/network/sync/src/lib.rs#L1921)). This leads to treating peers as having lower common numbers an requesting the same range from them after import. It looks like the logic in `on_block_queued()` relies exclusively on block numbers (not taking forks into account) to guess a new common number, so IMO it shouldn't be extended on `on_blocks_processed()` as is.
3. There are overlapping ranges in `BlockCollection`, even though it's designed to not have overlapping ranges: [logs](https://gist.github.com/dmitry-markin/2b67f85c9a8e19e09e7c1c50f1913578#file-gistfile1-txt-L86-L90).
4. There is inconsistency between import logic and `BlockCollection`: [here (logs)](https://gist.github.com/dmitry-markin/2b67f85c9a8e19e09e7c1c50f1913578#file-gistfile1-txt-L165-L166) we import only one block, but clear two blocks from `BlockCollection`.

Issues 1. & 2. are directly causing duplicate requests. https://github.com/paritytech/polkadot-sdk/pull/2045 addresses 1., but this is not enough to eliminate all cases of this invalid behavior. 

Note: logs for 3. and 4. are obtained already with https://github.com/paritytech/polkadot-sdk/pull/2045 applied, but this should not introduce these issues as the fix makes range allocation in `BlockCollection` stricter, not weaker.

**Comment by altonen** [comment]
What's weird is that why is this showing up now if these issues have been in `BlocksCollection` for a long time. There has been mainly trivial refactoring in syncing for the past couple of weeks so which of them surfaced up these issues.

**Comment by nazar-pc** [comment]
To me it like there were several long-standing issues, it is just now that we know when and why they are happnening.

**Comment by ggwpez** [comment]
Westend is lagging finalization currently with a surge in `Peerset` warnings:  

<img width="1417" alt="Screenshot 2023-10-31 at 17 19 48" src="https://github.com/paritytech/polkadot-sdk/assets/10380170/f8ec6464-9d00-41b8-a7e3-e2d36e4c7f49">

Again with logs of `Same block request multiple times`... warnings.

**Comment by altonen** [comment]
@dmitry-markin 

https://github.com/paritytech/polkadot-sdk/pull/2045 mentions that it improves the situation with duplicate block requests. Have you had time to look into what else is causing this?

**Comment by dmitry-markin** [comment]
> Westend relay is lagging again with these warnings. I dont know if they are a symptom of the cause of the issue though: ![Screenshot 

@ggwpez What version Westend is running? Is it running master with https://github.com/paritytech/polkadot-sdk/pull/2045 ?

**Comment by dmitry-markin** [comment]
> #2045 mentions that it improves the situation with duplicate block requests. Have you had time to look into what else is causing this?

@altonen No, it's hard to say what's happening without trace logs from Westend.

**Comment by xlc** [comment]
I am getting this error on our testnet

```
2024-07-30 02:54:36.634 WARN tokio-runtime-worker peerset: Report 12D3KooWNGzKvtT77z2tq3ihoF8jQh1TE3UeXwJTDEm6hRoF3tjw: -2147483648 to -2147483648. Reason: Same block request multiple times. Banned, disconnecting.
2024-07-30 02:54:36.211 WARN tokio-runtime-worker sync: Reserved peer 12D3KooWNGzKvtT77z2tq3ihoF8jQh1TE3UeXwJTDEm6hRoF3tjw disconnected 
```

**Comment by dmitry-markin** [comment]
Hi @xlc, if you are able to reproduce the error, could you collect the logs from the offending node sending duplicate requests? The logs needed are `-l sync=trace`. There are going to be a lot of logs, so let's start from 5 min interval before the duplicate request.

**Comment by xlc** [comment]
[logs.txt](https://github.com/user-attachments/files/16424735/logs.txt)
@dmitry-markin let me know if it is what you after

**Comment by dmitry-markin** [comment]
Is `Request to peer PeerId("12D3KooWPK694Lr3HduWxmwYpBeHRxUt75T9t8rgx6zUULD7cuNN") failed: Refused.` the result of the peer already being banned due to a duplicate request? Then we need 5 mins before this happened for the first time (the first duplicate request) to see what led to the duplicate request

**Comment by xlc** [comment]
how can I make the other peer to unban this peer so that I could try to reproduce it again?

**Comment by bkchr** [comment]
You need to restart the node.

@lexnv you already had a fix for this? Did we already merged it?

**Comment by xlc** [comment]
tried with parity/polkadot-parachain:1.15.0 and still having the same issue. will try to capture the logs after restart

**Comment by lexnv** [comment]
> I am getting this error on our testnet

Yep, we have a tentative fix: https://github.com/paritytech/polkadot-sdk/pull/5029, this aims to make things better when we have slow peers (overloaded nodes).

There's a potential other scenario that may happen, other than slow / overloaded nodes: 
- peer A sends a request to peer B
- peer B processes the request, but that leads to a failure `RequestFailure` 
- because of the failure, peer B disconnects immediately from the peer A
- peer A establishes another connection with peer B soon afterwards
- peer A sends the request again to peer B


We need more insight into what happened on the peer B side. Currently, litep2p will mark almost all failures as `Rejected` (although we can look into libp2p side).

I would say, in an ideal world, we'd have an optional `DisconnectReason` message propagated over the p2p-spec which would help us debug more issues in production

**Comment by xlc** [comment]
[logs.txt](https://github.com/user-attachments/files/16448006/logs.txt)

here is the new log. I can see two of
`New block request for 12D3KooWPK694Lr3HduWxmwYpBeHRxUt75T9t8rgx6zUULD7cuNN, (best:2319015, common:2307978)` which I guess is the reason why this peer got banned?

**Comment by dmitry-markin** [comment]
Yes, there are multiple requests to `12D3KooWPK694Lr3HduWxmwYpBeHRxUt75T9t8rgx6zUULD7cuNN` of `from: Number(2308042), direction: Descending, max: Some(64)`. Looks like some weird issue with the node being stuck on a different fork.

**Comment by xlc** [comment]
ok. do you still want anything or otherwise I will purge the nodes to fix our testnet

**Comment by dmitry-markin** [comment]
There is definitely something to look into on the syncing side (the node shouldn't be stuck on a fork). But I don't think we can do much with a DB already in this state. You can purge the nodes now, but if the issue manifests again, we will need to find a way to debug syncing (like collecting full logs during initial sync).
