### ISSUE TITLE
[Parachain] panicked at 'Invalid messaging state in relay chain state proof: DmqMqcHead(Proof)'

### ISSUE THREAD

**Issue by 3h4x** [paritytech/polkadot-sdk#2269]
Our t1rn on Kusama is stuck where the last block has applied the new runtime https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.t1rn.io#/explorer

Our collators show errors:
```
2023-11-10 11:23:00 [Parachain] Starting collation. relay_parent=0x8c74ae5b54cf414bc9cbb9c181988ad833e1dd0b5094c40d0843dc46049c0a29 at=0x96923a219410d3040e29cd34960c1a23d5fc6d3d8eceb4fbcea98df5cda6b5f0 |  
-- | --
  |   | 2023-11-10 11:23:00 [Relaychain] ✨ Imported #20494496 (0x8c74…0a29) |  
  |   | 2023-11-10 11:22:58 [Relaychain] 💤 Idle (13 peers), best: #20494495 (0x7962…e82e), finalized #20494491 (0xb8d0…16b0), ⬇ 374.8kiB/s ⬆ 672.7kiB/s |  
  |   | 2023-11-10 11:22:58 [Parachain] 💤 Idle (1 peers), best: #121761 (0x9692…b5f0), finalized #121761 (0x9692…b5f0), ⬇ 26 B/s ⬆ 37 B/s |  
  |   | 5: 0x4b52b9 - <unknown>!BlockBuilder_finalize_block |  
  |   | 4: 0x5c425f - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h617db0635172833f |  
  |   | 3: 0x43414d - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37,TupleElement38,TupleElement39,TupleElement40,TupleElement41,TupleElement42,TupleElement43,TupleElement44,TupleElement45,TupleElement46,TupleElement47) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h2f83ade10e9b8cde |  
  |   | 2: 0x5e0df0 - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<<<T as frame_system::pallet::Config>::Block as sp_runtime::traits::HeaderProvider>::HeaderT as sp_runtime::traits::Header>::Number>>::on_finalize::h0c4ba18e7eca556a |  
  |   | 1: 0x62776 - <unknown>!core::panicking::panic_fmt::h578d45979beca5ff |  
  |   | 0: 0x15294d - <unknown>!rust_begin_unwind |  
  |   | error while executing at wasm backtrace: |  
  |   | WASM backtrace: |  
  |   | 2023-11-10 11:22:54 [Parachain] Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed |  
  |   | set_validation_data inherent needs to be present in every block! |  
  |   | 2023-11-10 11:22:54 [Parachain] panicked at /home/sysi-epyc/.cargo/git/checkouts/cumulus-59522f43471fa161/0d17cf6/pallets/parachain-system/src/lib.rs:204:13: |  
  |   | 9: 0x4b5183 - <unknown>!BlockBuilder_apply_extrinsic. Dropping. |  
  |   | 8: 0x5c3c8d - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h85fa1eccad9a0165 |  
  |   | 7: 0x4c1556 - <unknown>!<t1rn_parachain_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h733d993d80fdff75 |  
  |   | 6: 0x4c42ce - <unknown>!<t1rn_parachain_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h5d17907952e7fc06 |  
  |   | 5: 0x506fab - <unknown>!frame_support::dispatch_context::run_in_context::h458ec88be87c8051 |  
  |   | 4: 0x4ff254 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::{{closure}}::h4827a50c04f6b731 |  
  |   | 3: 0x2de366 - <unknown>!frame_support::storage::transactional::with_transaction::h6d48acc58ae732ae |  
  |   | 2: 0x62ca1 - <unknown>!core::result::unwrap_failed::hdb74c69e6feaa347 |  
  |   | 1: 0x62776 - <unknown>!core::panicking::panic_fmt::h578d45979beca5ff |  
  |   | 0: 0x15294d - <unknown>!rust_begin_unwind |  
  |   | error while executing at wasm backtrace: |  
  |   | WASM backtrace: |  
  |   | 2023-11-10 11:22:54 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed |  
  |   | 2023-11-10 11:22:54 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back. |  
  |   | Invalid messaging state in relay chain state proof: DmqMqcHead(Proof) |  
  |   | 2023-11-10 11:22:54 [Parachain] panicked at /home/sysi-epyc/.cargo/git/checkouts/cumulus-59522f43471fa161/0d17cf6/pallets/parachain-system/src/lib.rs:431:18: |  
  |   | 2023-11-10 11:22:54 [Parachain] ⚠️ Circuit declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `NoStorageVersionSet` |  
  |   | 2023-11-10 11:22:54 [Parachain] ⚠️ XDNS declares internal migrations (which *might* execute). On-chain `StorageVersion(0)` vs current storage version `NoStorageVersionSet` |  
  |   | 2023-11-10 11:22:54 [Parachain] ⚠️ PolkadotXcm declares internal migrations (which *might* execute). On-chain `StorageVersion(1)` vs current storage version `StorageVersion(1)` |  
  |   | 2023-11-10 11:22:54 [Parachain] 🙌 Starting consensus session on top of parent 0x96923a219410d3040e29cd34960c1a23d5fc6d3d8eceb4fbcea98df5cda6b5f0 |  
  |   | 2023-11-10 11:22:54 [Parachain] Starting collation. relay_parent=0x796284ab833d13acf0e680cfaf74288edc156ed180e825b2f41e452dc1aee82e at=0x96923a219410d3040e29cd34960c1a23d5fc6d3d8eceb4fbcea98df5cda6b5f0 |  
  |   | 2023-11-10 11:22:54 [Relaychain] ✨ Imported #20494495 (0x7962…e82e) |  
  |   | 2023-11-10 11:22:53 [Relaychain] 💤 Idle (13 peers), best: #20494494 (0x0c3c…b63e), finalized #20494490 (0x8907…2923), ⬇ 580.1kiB/s ⬆ 941.9kiB/s |  
  |   | 2023-11-10 11:22:53 [Parachain] 💤 Idle (1 peers), best: #121761 (0x9692…b5f0), finalized #121761 (0x9692…b5f0), ⬇ 12 B/s ⬆ 12 B/s |  
  |   | 5: 0x4b52b9 - <unknown>!BlockBuilder_finalize_block |  
```
[More logs from collator](https://gist.github.com/3h4x/bb4e083b2cbc3d6922b48dd751784de0)

The upgrade was a chunky one, and incuded e.g. XCM upgrade to the next version v3. 
https://github.com/t3rn/t3rn/pull/1447

We did test a minimal runtime upgrade prior to that, and it went thru so we'd assume all the chainsepecs / genesis config is set correctly, also since the runtime upgrade was approved by Kusama.

This looks very similar to: 
- https://github.com/paritytech/cumulus/issues/2006 
- https://github.com/paritytech/subport/issues/565

**Comment by bkchr** [comment]
Hey, try upgrading your collators to the same version as you used for the runtime. This should fix the issue.

**Comment by 3h4x** [comment]
@bkchr Yeah, this is first thing that we did but the error persist.

**Comment by bkchr** [comment]
From which version are you migrating and to which version?

**Comment by 3h4x** [comment]
@bkchr We acutally didn't do any version upgrade. We had minimal shell running and we upgraded it to our proper testnet after checking all the chainsepecs / genesis config is set correctly. 
[This is PR with this runtime upgrade](https://github.com/t3rn/t3rn/pull/1447)

**Comment by bkchr** [comment]
So you only called `set_code`? Or what was the process you have done?

**Comment by 3h4x** [comment]
@bkchr That is correct sir. We called `set_code` in [this block ](https://cloudflare-ipfs.com/ipns/dotapps.io/?rpc=wss%3A%2F%2Frpc.t1rn.io#/explorer/query/0xe4ef88fd026d512a4fa52f49ddf6644db4f432935abbd74d5eb6e031464a536d)

**Comment by 3h4x** [comment]
Wasm is taken from our [GH release](https://github.com/t3rn/t3rn/releases/tag/v1.72.2-rc.0)

**Comment by MaciejBaj** [comment]
@bkchr would you have any further suggestions how to proceed with bringing the Parachain back to block production from here?

**Comment by bkchr** [comment]
@MaciejBaj https://github.com/t3rn/t3rn/blob/94135dfd797bcefdd7566c8474ea9c474bfa3c67/runtime/t0rn-parachain/src/xbi_config.rs#L200 looks like you changed your paraid to `3333` while it is actually `3334`?

**Comment by MaciejBaj** [comment]
that's clearly a mistake, thanks plenty for the find! we'll correct and go for the runtime upgrade via democracy on Kusama. feel free to close the issue if you think that the misconfigured paraId  in cumulus_pallet_parachain_system Config was the problem's root cause.

thanks again!

**Comment by bkchr** [comment]
Yeah, this will make reading from the relay chain state fail and thus, result in the error you are getting.
