### ISSUE TITLE
BUG: XCM transfer, that would slash account leads to total asset loss.

### ISSUE THREAD

**Issue by dudo50** [paritytech/polkadot-sdk#3050]
### Is there an existing issue?

- [X] I have searched the existing issues

### Experiencing problems? Have you tried our Stack Exchange first?

- [X] This is not a support question.

### Description of bug

There is huge bug, where, when account tries to transfer XCM Message that will also ~slash~ dust (cause to go below existential deposit) their account, the account will suffer total asset loss and XCM message will not get sent. This only occurs on Kusama Asset Hub, Polkadot works fine, because it does not have latest runtime.

### Steps to reproduce

Transfer amount that will result in less than existential deposit on Kusama Asset Hub (Kusama untested as I have verified identity there and do not want to loose it).

Or try any Kusama DEX and try transfer MAX option. (Kusama Asset Hub -> Kusama)
<img width="1440" alt="Screenshot 2024-01-24 at 16 34 47" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/a813ad39-3ae6-4102-8ed8-3aa4beaed966">

Other XCM transfers work as expected. Please, fix this bug as it could lead to huge asset losses if released on Polkadot also.

**Comment by KiChjang** [comment]
Which functionality did you use to transfer assets? Was it a teleport, or did you create your own XCM program? If it's the latter, can you show us your XCM program?

**Comment by dudo50** [comment]
> Which functionality did you use to transfer assets? Was it a teleport, or did you create your own XCM program? If it's the latter, can you show us your XCM program?

Hey @KiChjang , we used native PolkadotXCM and limited teleport function. 
<img width="1440" alt="Screenshot 2024-01-24 at 16 34 26" src="https://github.com/paritytech/polkadot-sdk/assets/55763425/aac3a811-1859-44ec-8adf-5f975ba2be7d">

Here is how the message was formatted (other messages are formatted the same but would not slash account work just fine)

**Comment by ggwpez** [comment]
Apparently its this block: https://assethub-kusama.subscan.io/block/6284878?tab=event  
And this state diff: [diff.html.txt](https://github.com/paritytech/polkadot-sdk/files/14041821/diff.html.txt)

**Comment by kianenigma** [comment]
I tried to emulate this issue using Chopsticks and at first attempt couldn't. Are you claiming that any teleport that leaves the sender below existential deposit on the kusama relay chain will cause a trap? I moved 5 KSM To Charlie, teleported 4.999999 to Charlie on AH and the teleport failed with a reasonable outcome, without any traps or loss of funds.

**Comment by dudo50** [comment]
@kianenigma If I understand you correctly, you tried Kusama -> AssetHub transfer. We encountered the issue on AssetHub->Kusama transfer.

**Comment by dudo50** [comment]
I am still able to recreate it, so it was not temporary: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/explorer/query/0xd3191feabfc50b1c6415f2fd70cd704d77e3a61558e15721d20baf874732fcc6

**Comment by NachoPal** [comment]
I tried a `limitedTeleport` from AssetHubKusama to Kusama with Chopsticks and it worked.

Some edge case should be triggering your case.

**Comment by NachoPal** [comment]
Can you share what was your balance when you tried to do the teleport and how much KSM you tried to teleport?

Not sure if I understand the issue, I am not able to reproduce it. I tried to teleport all my balance and it failed because a fee has to be paid beforehand. However, the sending account does not lose all its balance, just the mentioned fee.

**Comment by dudo50** [comment]
You can find my approximate balance here:
Around 0.04ksm. https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x8d02840084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b01988575310511e1dc64f6a1d041d9ca0be73beaf8c90c04f5949d89cbdefaf2768990d1c4853db0f4492eac27410aba4f7b2a87d46b918c49267086dc3402278b04018800001f09030100030001010084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b030400010000075ab2966e0b0000000000

**Comment by dudo50** [comment]
> Can you share what was your balance when you tried to do the teleport and how much KSM you tried to teleport?
> 
> Not sure if I understand the issue, I am not able to reproduce it. I tried to teleport all my balance and it failed because a fee has to be paid beforehand. However, the sending account does not lose all its balance, just the mentioned fee.

What was the call you used and how much was your balance/you tried to send? We are always sending amount-xcmfee*1.5. Not the entire amount because then it would fail as expected with inability to pay for fees.

**Comment by dudo50** [comment]
If you go to any dex, for eg Karura or Basilisk and go to cross-chain section and hit transfer max button you should be able to replicate. Be sure to not have lots of coins though.

**Comment by NachoPal** [comment]
> You can find my approximate balance here:
Around 0.04ksm. https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x8d02840084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b01988575310511e1dc64f6a1d041d9ca0be73beaf8c90c04f5949d89cbdefaf2768990d1c4853db0f4492eac27410aba4f7b2a87d46b918c49267086dc3402278b04018800001f09030100030001010084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b030400010000075ab2966e0b0000000000

I meant what was the balance in your account, not the amount you tried to teleport

**Comment by dudo50** [comment]
> > You can find my approximate balance here:
> Around 0.04ksm. https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-asset-hub-rpc.polkadot.io#/extrinsics/decode/0x8d02840084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b01988575310511e1dc64f6a1d041d9ca0be73beaf8c90c04f5949d89cbdefaf2768990d1c4853db0f4492eac27410aba4f7b2a87d46b918c49267086dc3402278b04018800001f09030100030001010084fc49ce30071ea611731838cc7736113c1ec68fbc47119be8a0805066df9b2b030400010000075ab2966e0b0000000000
> 
> I meant what was the balance in your account, not the amount you tried to teleport

I am unable to give you certain number as as I mentioned it was approximately same as was sent. This is the condition to catch the bug: balance-(amount+xcmfee×1.5)>0 && < ED.

**Comment by dudo50** [comment]
Here is a demonstration of the bug in the video.
And you can try any dex not just Karura dex..

So now you know how to replicate it I believe, because I really have no other way to show you now. I've tried my best.

https://github.com/paritytech/polkadot-sdk/assets/55763425/1abd52ea-a8e5-48e4-a081-1e384ca1dd9c

**Comment by NachoPal** [comment]
Thanks for the video, much clear now. I had to use exactly the same amounts to be able to reproduce the case.

You account does not go to 0 KSM. I checked and your balance after trying the teleport was: `96,375,486`. It is UI issue because of not having enough decimals.

I think the issue was introduced in https://github.com/paritytech/polkadot-sdk/pull/1234

As per the **Important Note** states in the PR, the UI should have taken into consideration the new delivery fee, disallowing you from doing the teleport.

Initially you have enough balance to pay for the transaction fee + the first `WithdrawAsset` (amount to teleport). However, after the first withdrawal, when trying to [send the message](https://github.com/paritytech/polkadot-sdk/blob/release-crates-io-v1.3.0/polkadot/xcm/xcm-executor/src/lib.rs#L687), it tries to [take the fee](https://github.com/paritytech/polkadot-sdk/blob/release-crates-io-v1.3.0/polkadot/xcm/xcm-executor/src/lib.rs#L408), subsequently failing when trying to [withdraw again](https://github.com/paritytech/polkadot-sdk/blob/release-crates-io-v1.3.0/polkadot/xcm/xcm-executor/src/lib.rs#L976) as the holding registry does not have enough funds anymore.

I think this issue is solved by https://github.com/paritytech/polkadot-sdk/pull/2388 and https://github.com/paritytech/polkadot-sdk/pull/1222

Let me confirm it and see if we can patch it.

**Comment by dudo50** [comment]
Perfect! Thanks for the great explanation! Much clearer on my end now too!

**Comment by rageruun** [comment]
can anyone help? Tokens stuck in parachain bridge when transmitted from the Kusama network to the Moonriver (xcKSM)
![image](https://github.com/paritytech/polkadot-sdk/assets/95443486/a062e53e-8ec6-4d8b-84cc-1c5226ccb7ea)
hash https://kusama.subscan.io/extrinsic/0x37b705c316c4b4b8d552964a130a552e06bad1f55171fca693e4b4e1917dd336?tab=event

**Comment by KiChjang** [comment]
The tokens are not stuck in the bridge, but rather in the sovereign account of parachain 2023: https://kusama.subscan.io/account/F7fq1jSB3w59f8vMShxvP5eSu3wCJbL5Am5MQ6vP6VzYLWD.

Easiest way to recover this is to contact support on parachain 2023 and show them this exact extrinsic (or this issue), and tell them that you have a failed teleport, and now some assets are stuck in their sovereign account, and that you want to retrieve them.

For now, please refrain from using the send MAX functionality of all XCM UIs, since it appears that none of them took account of the delivery fees, leading to this bug. Instead, send most of your KSM and leave behind maybe 1 KSM to pay for delivery fees -- this should avoid non-payment of fees.

**Comment by rageruun** [comment]
Awesome, thanks for the update!

вт, 30 янв. 2024 г. в 14:48, Adrian Catangiu ***@***.***>:

**Comment by KiChjang** [comment]
@acatangiu Not quite, this issue uses teleport, whereas the fixes we have resolve reserve asset transfers.

**Comment by KiChjang** [comment]
Sorry, it looks like @rageruun here is talking about a reserve asset transfer, which is not exactly related to what the original post is about.

**Comment by rageruun** [comment]
https://kusama.subscan.io/extrinsic/21594113-4
![image](https://github.com/paritytech/polkadot-sdk/assets/95443486/04b63d58-a6f5-47a5-ab17-d13732e5b434)

**Comment by acatangiu** [comment]
> @acatangiu Not quite, this issue uses teleport, whereas the fixes we have resolve reserve asset transfers.

I believe [XCM transactional processing](https://github.com/paritytech/polkadot-sdk/pull/3113) also fixes/mitigates this issue.

**Comment by acatangiu** [comment]
This should be fixed in runtimes patch release https://github.com/polkadot-fellows/runtimes/releases/tag/v1.1.2

**Comment by dudo50** [comment]
Sorry to hear this @Pescador1551 , the fix is currently being issued via opengov. Good luck recovering your assets!

**Comment by dudo50** [comment]
@acatangiu , the issue is still not resolved and after Polkadot runtime update users are now loosing assets on Polkadot. Could you reopen? It seems to be issue with when they send XCM transfer that also dusts their account.

**Comment by acatangiu** [comment]
this was fixed back in November in https://github.com/paritytech/polkadot-sdk/pull/2405 and first released in polkadot sdk v1.5.0

problem 1. is it wasn't backported to sdk 1.3 or 1.4
problem 2. is fellowship/runtimes is running considerably behind polkadot-sdk so the fix just hasn't hit live runtimes yet

Opened https://github.com/polkadot-fellows/runtimes/issues/210 to track inclusion of this fix in the runtime releases

**Comment by dudo50** [comment]
Thanks @acatangiu for quickly letting us know! The function for asset recovery will be awesome to have!

**Comment by rageruun** [comment]
tnks for msg

чт, 29 февр. 2024 г. в 17:24, Dusan Morhac ***@***.***>:

**Comment by Polkadot-Forum** [comment]
This issue has been mentioned on **Polkadot Forum**. There might be relevant details there:

https://forum.polkadot.network/t/discussion-retroactive-big-tipper-xcm-lens-v0-0-2-xcm-debugging-toolkit-136-tests-mit/17784/1
