### ISSUE TITLE
Terrible error message for the runtime macro

### ISSUE THREAD

**Issue by xlc** [paritytech/polkadot-sdk#4347]
Code: https://github.com/open-web3-stack/XCQ/blob/b73637cc5916f2ccd3f40225979e8ef2ddb809d2/poc/runtime/src/lib.rs
`SKIP_WASM_BUILD= cargo check -p poc-runtime`

```
error: expected one of `!` or `::`, found identifier `deps`
  --> poc/runtime/src/lib.rs:63:1
   |
63 | #[runtime]
   | ^^^^^^^^^^
   | |
   | expected one of `!` or `::`
   | in this macro invocation
   |
   = note: this error originates in the macro `pallet_transaction_payment::tt_default_parts_v2` which comes from the expansion of the attribute macro `runtime` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0432]: unresolved import `super::Runtime`
   --> poc/runtime/src/lib.rs:231:6
    |
231 |     use super::Runtime;
    |         ^^^^^^^-------
    |         |      |
    |         |      help: a similar name exists in the module: `runtime`
    |         no `Runtime` in the root
```

I am creating a new runtime using the minimal template https://github.com/paritytech/polkadot-sdk/blob/master/templates/minimal/runtime/src/lib.rs.

There is zero chance a new dev can figure it out. And I have already wasted 30mins on this already and still unsure what's wrong.

**Comment by xlc** [comment]
maybe it is related to https://github.com/paritytech/polkadot-sdk/issues/4348. I figured it by out switching to the old construct_runtime macro. The error message is still not obvious but at least it provides enough hint for me to investigate

**Comment by gupnik** [comment]
Thanks for reporting it. This is an issue with the usage of the `runtime` macro and the `polkadot-sdk-frame` crate. It was merged a couple of days back [here](https://github.com/paritytech/polkadot-sdk/pull/4119) but the  `polkadot-sdk-frame` has not been updated yet. 

@Morganamilo Could you please check why it wasn't published with the latest release?

**Comment by rzadp** [comment]
In case it's useful, [here](https://github.com/paritytech-stg/polkadot-sdk-minimal-template/tree/update-template/1.11.0) is the minimal template moved out of the monorepo, based on `release-polkadot-v1.11.0` branch.

Building fails with:

```
     Compiling pallet-minimal-template v0.1.0 (/snip/pallets/template)
  warning: unstable feature specified for `-Ctarget-feature`: `sign-ext`
    |
    = note: this feature is not stably supported; its behavior can change in the future

  warning: `pallet-minimal-template` (lib) generated 1 warning
  error[E0432]: unresolved imports `frame::deps::frame_support::genesis_builder_helper::build_state`, `frame::deps::frame_support::genesis_builder_helper::get_preset`
    --> /snip/runtime/src/lib.rs:26:28
     |
  26 |         genesis_builder_helper::{build_state, get_preset},
     |                                  ^^^^^^^^^^^  ^^^^^^^^^^ no `get_preset` in `genesis_builder_helper`
     |                                  |
     |                                  no `build_state` in `genesis_builder_helper`

  error[E0152]: duplicate lang item in crate `sp_io` (which `frame_support` depends on): `panic_impl`.
    |
    = note: the lang item is first defined in crate `sp_io` (which `frame_support` depends on)
    = note: first definition in `sp_io` loaded from /snip/target/debug/wbuild/minimal-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-0393cee24198b376.rmeta
    = note: second definition in `sp_io` loaded from /snip/target/debug/wbuild/minimal-template-runtime/target/wasm32-unknown-unknown/release/deps/libsp_io-d70d1d04bae80db5.rmeta

  Some errors have detailed explanations: E0152, E0432.
  For more information about an error, try `rustc --explain E0152`.
  error: could not compile `minimal-template-runtime` (lib) due to 2 previous errors
```

---

Seems to me like it's also caused by https://github.com/paritytech/polkadot-sdk/issues/4348.

**Comment by gupnik** [comment]
The latest version has been published. This should be fixed now.

**Comment by xlc** [comment]
but one of the root causes is the bad error message and that’s not fixed. it is very easy for someone to introduce incompatible deps and they will end up with the same situation

**Comment by gupnik** [comment]
> but one of the root causes is the bad error message and that’s not fixed. it is very easy for someone to introduce incompatible deps and they will end up with the same situation

I don't quite understand the expectation here. If a change in Crate A depends on the next version of Crate B, do you expect an error message asking someone to update the dependency if they end up using the older version? 

If one uses the versions as per https://github.com/paritytech/psvm, this shouldn't happen at all. This was a specific case where the upstream was released but the dependency wasn't.

**Comment by kianenigma** [comment]
- If the older version of `polkadot-sdk-frame` is possibly buggy it should be yanked. Although I would argue it is experimental so we can also skip that. 
- If this error is something that is possible to be reached again (which based on my understanding it is _not_) the error message should be better.

**Comment by gupnik** [comment]
> If the older version of polkadot-sdk-frame is possibly buggy it should be yanked. Although I would argue it is experimental so we can also skip that.

The older one is also not buggy and works with the older versions of polkadot-sdk. It's just that the latest release pushed yesterday didn't push the updates for this crate, causing a mismatch.

**Comment by xlc** [comment]
I know it is a user error but it doesn’t change the fact that it will happen regardless. yes pavm is helpful but it doesn’t solve all the problems. 
for example, someone could use orml pallet that haven’t updated to support latest polkadot-sdk version yet. and I don’t think psvm supports orml or other non polkadot-sdk pallet anyway so there are still some manual bumping needed and it will go wrong for someone in future
