### ISSUE TITLE
p2p performance issues, regression?

### ISSUE THREAD

**Issue by rvalle** [paritytech/polkadot-sdk#6012]
Hi!

We run full archive nodes for our analytics project. Typically we run on constrained resources. Our nodes typically run like clockwork with 2 peer in/out configuration.

Recently we updated our Polkadot node from docker version: v1.15.1 to v1.16.0 and p2p is starting to get stuck, even after doubling the peer count. This is something that we reported in the past, and perhaps for some reason, there was some kind of regression.

Here is what we are seeing now:

![24h Screenshot 2024-10-10 at 15-21-57 View panel - Polkadot Node Monitoring - Starred - Grafana](https://github.com/user-attachments/assets/64280d02-7c78-4ca9-a99a-667040e48b3a)

Prior to this upgrade, p2p would not stuck at all, our very very rarely and for very little block could:

![v1 15 1 Screenshot 2024-10-10 at 15-25-22 View panel - Polkadot Node Monitoring - Starred - Grafana](https://github.com/user-attachments/assets/34cd55b0-2807-457f-9239-3c36d506db84)

We reported a similar issue in the past, here is some reference: https://github.com/paritytech/polkadot/issues/6696#issuecomment-1495424865

Back them it was fixed.

**Comment by lexnv** [comment]
The issues was fixed in the past with:
- https://github.com/paritytech/substrate/pull/13829 

That fix has been reverted by:
- https://github.com/paritytech/polkadot-sdk/pull/3983

cc perf issue: https://github.com/paritytech/polkadot-sdk/issues/5221

**Comment by lexnv** [comment]
We still need to double-check this issue, it might expose some regressions we introduced between 0.15 and 0.16.

The perf issue should already affect 0.15, cc'ed to make sure we don't forget to check protocol performance (which we might have missed with libp2p update)

**Comment by rvalle** [comment]
@lexnv yes, 0.15 is also affected, attempted a rollback and issue is still there. Also notice bandwidth usage is in the order of 5x, when using low peer numbers. this was also reported before, and most possibly related.

**Comment by rvalle** [comment]
@lexnv I have not tested a lot, but today I changed to the little p2p backend, and it seems to be free from the issue:

![Screenshot 2024-10-15 at 17-13-43 View panel - Polkadot Node Monitoring - Starred - Grafana](https://github.com/user-attachments/assets/e93dd7eb-9ef2-4fc0-b6dc-0207dc429853)

I would say that the bandwidth usage has increased compared to the pre-regression version but not as much as with the default implementation.
