### ISSUE TITLE
bench bot - didn't push generated weights

### ISSUE THREAD

**Issue by bkontur** [paritytech/polkadot-sdk#8195]
I tried to generate weights with bench bot, looks like it generated weights - I can see the diff: https://github.com/paritytech/polkadot-sdk/actions/runs/14285615346/job/40040334210#step:5:8228,
but did not push to the PR, and I can see just this error:

https://github.com/paritytech/polkadot-sdk/actions/runs/14285615346
![Image](https://github.com/user-attachments/assets/2b55af8e-8897-4d54-9133-ccc35aa6636a)

**Comment by bkontur** [comment]
even for single runtime with single pallet  bot does not push:
https://github.com/paritytech/polkadot-sdk/actions/runs/14355684046

**Comment by alvicsam** [comment]
Actually no, external contributors can also use the bot. The problem is weird, the `cmd` step has successfully ended so the `after-cmd` step should've also finished and pushed the changes to the PR. However github shows an error and skipped the `after-cmd` job. I tried running the `/cmd bench --runtime asset-hub-westend --pallet pallet_xcm_benchmarks::generic` command on staging but I couldn't reproduce the issue. I'll try other options.

**Comment by serban300** [comment]
I'm having the same issue here: https://github.com/paritytech/polkadot-sdk/pull/8344

 I tried to download the diff and apply it, but the problem is that `git apply` fails. However, the patch looks correct and I managed to apply it from rustrover. So I think there might be some formatting issue when the bot creates the patch. Maybe something related to `git diff`.

**Comment by alvicsam** [comment]
I've returned from ooo and will continue on the issue.

**Comment by alvicsam** [comment]
So it seems that the only reason why github skips `after-cmd` step is the `Job outputs has exceeded maximum size` error. The last job (`finish`) works because it has the `always()` condition. I'll reduce output of scripts and actions and push the changes.

**Comment by alvicsam** [comment]
@serban300 I've merged [my PR](https://github.com/paritytech/polkadot-sdk/pull/8407) and tried the command `/cmd bench --pallet cumulus_pallet_xcmp_queue` in a [test PR](https://github.com/paritytech/polkadot-sdk/pull/8410) and it worked. Could you please rebase your branch and try again?

**Comment by serban300** [comment]
@alvicsam done, I rebased my branch and tried again. It still fails:
https://github.com/paritytech/polkadot-sdk/pull/8344#issuecomment-2850290505

**Comment by alvicsam** [comment]
This is really weird 0_o Okay, I'll to create a PR from fork and running commands there.

**Comment by alvicsam** [comment]
It seems, that I've found the issue. cmd-bot [puts the output](https://github.com/paritytech/polkadot-sdk/blob/master/.github/workflows/cmd-run.yml#L245-L250) of the `subweigt` command to `GITHUB_OUTPUT` in order to pass it to the next step. And now in some cases the output is more 1MB, that's why the job fails. I'll continue working on the fix.

**Comment by alvicsam** [comment]
I applied a [quick fix](https://github.com/paritytech/polkadot-sdk/commit/b48d410afbd72c4ad334e443936019a1b00be5ce) so cmd-bot will not print results if they exceed the output size limit and [it works](https://github.com/paritytech/polkadot-sdk/pull/8344#issuecomment-2851410847). I'll think of how to make the output more user-friendly.
