### ISSUE TITLE
`fatxpool`: add one more fallback for `ready_at_light`

### ISSUE THREAD

**Issue by michalkucharczyk** [paritytech/polkadot-sdk#8213]
In general we need one more fallback in [`ready_at_light`](https://github.com/paritytech/polkadot-sdk/blob/27fbb06d4b17178da50cc043ef5ec60b0cdfead8/substrate/client/transaction-pool/src/fork_aware_txpool/fork_aware_txpool.rs#L558-L565). We should blindly provide `txs` from [`most_recent_view`](https://github.com/paritytech/polkadot-sdk/blob/27fbb06d4b17178da50cc043ef5ec60b0cdfead8/substrate/client/transaction-pool/src/fork_aware_txpool/view_store.rs#L167-L169) if other methods failed.

The justification is as follows:

> The only possible argument to make it work in this stress conditions would be that, maybe you want some transactions to go through, so that if for recovering/fixing you need to apply some runtime/storage configuration changes you can do it.

Quick sketch of what happened (the real root cause was misconfiguration of collators):
```
B1f - B2f - B3f (constructed)
|
B2
 |
B3
```

Pool knows about `B3`.
Then we finalized `B1f`.
And try to build on top of `B2f`

`ready_at_light` is first computing tree route from new parent (`B2f`) to  finalized block.
And then looks for any views on enacted part. But we have no - because pool only saw `B3`.

Here is log and figures:
```
txpool: [Parachain] maintain txs=(0, 1) a=3 i=0 views=[(69018, 1, 0), (69019, 1, 0), (69020, 1, 0)] event=Finalized { hash: BLOCK69017f03, tree_route: [] } duration=70.143µs
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
substrate: [Relaychain] 💤 Idle (3 peers), best: #73024 (RBLOCK73024), finalized #73022 (RBLOCK73022), ⬇ 0.9kiB/s ⬆ 0.7kiB/s    
substrate: [Parachain] 💤 Idle (1 peers), best: #69020 (BLOCK69020), finalized #69017 (BLOCK69017f03), ⬇ 45 B/s ⬆ 35 B/s    
substrate: [Relaychain] 🏆 Imported #73025 (RBLOCK73024 → RBLOCK73025)    
parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=RBLOCK73022
parachain::collator-protocol: [Relaychain] Collation was requested. candidate_hash=GOBO pov_hash=NAPE traceID=217006037283171539261327901027945344636
sc_informant: [Parachain] ♻️  Reorg on #69020,BLOCK69020 to #69021,BLOCK69021, common ancestor #69017,BLOCK69017f03    
substrate: [Parachain] 🏆 Imported #69021 (BLOCK69020f01 → BLOCK69021)    
txpool: [Parachain] maintain txs=(0, 1) a=4 i=0 views=[(69018, 1, 0), (69019, 1, 0), (69020, 1, 0), (69021, 1, 0)] event=NewBestBlock { hash: BLOCK69021, tree_route: Some(TreeRoute { route: [HashAndNumber { number: 69020, hash: BLOCK69020 }, HashAndNumber { number: 69019, hash: BLOCK69019f01 }, HashAndNumber { number: 69018, hash: BLOCK69018f02 }, HashAndNumber { number: 69017, hash: BLOCK69017f03 }, HashAndNumber { number: 69018, hash: BLOCK69018f03 }, HashAndNumber { number: 69019, hash: BLOCK69019f02 }, HashAndNumber { number: 69020, hash: BLOCK69020f01 }], pivot: 3 }) } duration=611.833µs
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
substrate: [Relaychain] 💤 Idle (3 peers), best: #73025 (RBLOCK73025), finalized #73022 (RBLOCK73022), ⬇ 0.9kiB/s ⬆ 0.7kiB/s    
substrate: [Parachain] 💤 Idle (1 peers), best: #69021 (BLOCK69021), finalized #69017 (BLOCK69017f03), ⬇ 1.8kiB/s ⬆ 95 B/s    
substrate: [Relaychain] 🏆 Imported #73026 (RBLOCK73025 → RBLOCK73026)    
parachain::collator-protocol: [Relaychain] Removing relay parent because our view changed. relay_parent=RBLOCK73023
sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent BLOCK69018f03 (#69018)    
txpool: [Parachain] Timeout fired waiting for transaction pool at block. Proceeding with production. at=BLOCK69018f03
basic-authorship: [Parachain] Attempting to push transactions from the pool at BLOCK69018f03.    
basic-authorship: [Parachain] No more transactions, proceeding with proposing.    
sc_basic_authorship::basic_authorship: [Parachain] 🎁 Prepared block for proposing at 69019 (168 ms) hash: ANTA; parent_hash: BLOCK69018f03; end: NoMoreTransactions; extrinsics_count: 2    
aura::cumulus: [Parachain] 🔖 Pre-sealed block for proposal at 69019. Hash now BLOCK69019f03, previously ANTA.
substrate: [Parachain] 🆕 Imported #69019 (BLOCK69018f03 → BLOCK69019f03)    
aura::cumulus: [Parachain] PoV size { header: 0.22265625kb, extrinsics: 3.76171875kb, storage_proof: 10.5107421875kb }
aura::cumulus: [Parachain] Compressed PoV size: 13.4951171875kb
parachain::collation-generation: [Relaychain] candidate is generated candidate_hash=DOER pov_hash=BICK relay_parent=RBLOCK73026 para_id=3369 core_index=CoreIndex(0) traceID=255551800300830200024247885740631521910
parachain::collator-protocol: [Relaychain] Received session info session_index=135
parachain::collator-protocol: [Relaychain] Accepted collation, connecting to validators. para_id=3369 candidate_relay_parent=RBLOCK73026 candidate_hash=DOER pov_hash=BICK core=CoreIndex(0) current_validators=[Public(d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d (XUtEtdq5...)), Public(8eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48 (XUrfjMku...))] traceID=255551800300830200024247885740631521910
sc_basic_authorship::basic_authorship: [Parachain] 🙌 Starting consensus session on top of parent BLOCK69019f03 (#69019)    
parachain::collator-protocol: [Relaychain] Advertising collation. relay_parent=RBLOCK73026 candidate_hash=DOER peer_id=12D3KooWQCkBm1BYtkHpocxCwMgR8yjitEeHGx8spzcDLGt2gkBm traceID=255551800300830200024247885740631521910
parachain::collator-protocol: [Relaychain] Advertising collation. relay_parent=RBLOCK73026 candidate_hash=DOER peer_id=12D3KooWRkZhiRhsqmrQ28rt73K7V3aCBpqKrLGSXmZ99PTcTZby traceID=255551800300830200024247885740631521910
parachain::validator-discovery: [Relaychain] New ConnectToValidators request peer_set=Collation requested=2 failed_to_resolve=0
parachain::validator-discovery: [Relaychain] New ConnectToValidators resolved request peer_set=Collation num_peers=2 removed=0
txpool: [Parachain] Timeout fired waiting for transaction pool at block. Proceeding with production. at=BLOCK69019f03
basic-authorship: [Parachain] Attempting to push transactions from the pool at BLOCK69019f03.    
basic-authorship: [Parachain] No more transactions, proceeding with proposing.    
sc_basic_authorship::basic_authorship: [Parachain] 🎁 Prepared block for proposing at 69020 (168 ms) hash: POSY; parent_hash: BLOCK69019f03; end: NoMoreTransactions; extrinsics_count: 2
```

Finalized blocks:
<img src="https://github.com/user-attachments/assets/51960c6d-1620-429d-b586-625ccfa7eaf5" width=50% height=50%>

Known Best Blocks:
<img src="https://github.com/user-attachments/assets/20962111-3ff9-4f62-835b-a6b216c5e087" width=50% height=50%>

**Comment by michalkucharczyk** [comment]
@alexggh would you please provide the `misconfiguration` that lead to that problem so we can cross-check if the fix work?

**Comment by alexggh** [comment]
> @alexggh would you please provide the misconfiguration that lead to that problem so we can cross-check if the fix work?

The misconfiguration was that I was running a tesnet paseo relay chain wich has `configuration.scheduling_params. lookahead` set to 1, and a parachain with async backing, so blocks were being dropped but all production relay chains already have `lookahed` set to 3, which is the right value, so I don't expect anyone else to hit this problem in production.

**Comment by michalkucharczyk** [comment]
Also related: https://github.com/paritytech/polkadot-sdk/issues/5492 (I'd say root cause).

**Comment by wilwade** [comment]
I also just ran into this when testing for forcing the Frequency chain over to fatxpool.

**Comment by michalkucharczyk** [comment]
Would you please elaborate more?

Is problem you faced:  `Finalized` blocks are not reported as `NewBestBlock` to the pool?
or
No transactions are getting to the block? And if yes - does it happen all the time or just some blocks are empty?

**Comment by wilwade** [comment]
@michalkucharczyk Blocks do get finalized, but transactions were not getting into any finalized block.

Here's what the PAPI showed for with lookahead=1 (See the transaction in the unfinalized fork)

![Image](https://github.com/user-attachments/assets/9ba653b1-3e53-4907-bab5-1b8c58b18222)

The forks were just going crazy.

Then it would get dropped as that fork gets overwritten:

![Image](https://github.com/user-attachments/assets/3b6898f3-5a9b-4323-8db3-077a07900ada)

Change it to lookahead=2

![Image](https://github.com/user-attachments/assets/7d14410b-4b98-4662-b90e-ae327cc6dfc8)

You can actually see that the fatxpool did its job. That balances transfer you see in the events is the SAME one that was failing in the prior screenshots

**Comment by michalkucharczyk** [comment]
Is my understanding correct, that problem is now fixed? And the original root cause was incorrect value of lookahead?

Obiously the pool still needs the fix to avoid this bug.

**Comment by wilwade** [comment]
> Is my understanding correct, that problem is now fixed? And the original root cause was incorrect value of lookahead?

It is still an issue on Paseo Local due to the config, but there is a separate issue for that: https://github.com/paseo-network/runtimes/issues/199

**Comment by wilwade** [comment]
Ok. Might be running into another issue that I think is related to this, although having a bit of trouble tracking it down (could be something new).

Reasons I think it is related:
1. Triggered by about a 1-4 transactions per block testing
2. I get a ton of `Timeout fired waiting for transaction pool at block. Proceeding with production` warnings.
3. Forks start exploding (see image below)
![Image](https://github.com/user-attachments/assets/99bfdbe8-090b-49ce-9f70-ec9a89bb6c4d)

Here are the logs with `txpool=trace`
This is from a new Frequency Testnet running against Westend (lookahead: 3)

https://gist.github.com/wilwade/b1a321a3194d4bf613cc1239c14aa5cc

**Comment by michalkucharczyk** [comment]
This forking does not look as something we would expect - seems like some misconfiguration maybe(cc: @skunert).

A lot of blocks imported as _new_ but not _new best block_. The _new_ are not notified to the transaction pool.

So yeah, this looks like the problem originally described in this issue - the finalized block was not notified to the pool.
As I know there is some work in progress to fix this problem (cc: @iulianbarbu).

<details>
<summary> imported logs </summary>

```
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #502 (HAZY → BLOCK502)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #503 (BLOCK502 → BLOCK503)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #502 (HAZY → BLOCK502f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #503 (BLOCK502f01 → BLOCK503f01)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #504 (BLOCK503f01 → BLOCK504)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #505 (BLOCK504 → BLOCK505)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #506 (BLOCK505 → BLOCK506)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #507 (BLOCK506 → BLOCK507)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #508 (BLOCK507 → BLOCK508)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #509 (BLOCK508 → BLOCK509)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #510 (BLOCK509 → BLOCK510)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #511 (BLOCK510 → BLOCK511)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #509 (BLOCK508 → BLOCK509f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #510 (BLOCK509f01 → BLOCK510f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #509 (BLOCK508 → BLOCK509f02)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #510 (BLOCK509f02 → BLOCK510f02)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f01 → BLOCK511f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f01 → BLOCK511f02)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #509 (BLOCK508 → BLOCK509f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #510 (BLOCK509f03 → BLOCK510f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f03 → BLOCK511f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #509 (BLOCK508 → BLOCK509f04)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #510 (BLOCK509f04 → BLOCK510f04)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #509 (BLOCK508 → BLOCK509f05)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #510 (BLOCK509f05 → BLOCK510f05)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f05 → BLOCK511f04)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f05 → BLOCK511f05)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #511 (BLOCK510f05 → BLOCK511f06)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #530 (SIFE → BLOCK530)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #528 (LOCI → BLOCK528)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #529 (BLOCK528 → BLOCK529)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #530 (BLOCK529 → BLOCK530f01)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #531 (BLOCK530f01 → BLOCK531)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #532 (BLOCK531 → BLOCK532)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #533 (BLOCK532 → BLOCK533)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #534 (BLOCK533 → BLOCK534)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533 → BLOCK534f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #533 (BLOCK532 → BLOCK533f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533f01 → BLOCK534f02)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #535 (BLOCK534f02 → BLOCK535)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #535 (BLOCK534f02 → BLOCK535f01)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #533 (BLOCK532 → BLOCK533f02)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533f02 → BLOCK534f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #533 (BLOCK532 → BLOCK533f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533f03 → BLOCK534f04)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #535 (BLOCK534f03 → BLOCK535f02)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #533 (BLOCK532 → BLOCK533f04)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533f04 → BLOCK534f05)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #535 (BLOCK534f05 → BLOCK535f03)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #533 (BLOCK532 → BLOCK533f05)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #534 (BLOCK533f05 → BLOCK534f06)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #535 (BLOCK534f06 → BLOCK535f04)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #536 (BLOCK535f04 → BLOCK536)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #537 (BLOCK536 → BLOCK537)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #538 (BLOCK537 → BLOCK538)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #538 (BLOCK537 → BLOCK538f01)
INFO tokio-runtime-worker substrate: [Parachain] 🏆 Imported #539 (BLOCK538 → BLOCK539)
INFO tokio-runtime-worker substrate: [Parachain] 🆕 Imported #539 (BLOCK538 → BLOCK539f01)
```

</details>

<details>

<summary> forks pic </summary>

![Image](https://github.com/user-attachments/assets/72487fe6-0b2f-4439-af3f-41ce3781e14e)

</details>
