### ISSUE TITLE
Dispute storms on validators running v.16 or lower on kusama after runtime upgrade

### ISSUE THREAD

**Issue by alexggh** [paritytech/polkadot-sdk#8481]
After the runtime upgrade and the setting of nodeFeatures to `0b11010000`, validators running polkadot  that is v1.16 or lower are disputing candidates.

Runtime upgrade happened here: https://kusama.subsquare.io/referenda/519?tab=metadata

Issue started happening after https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fkusama-rpc.dwellir.com#/explorer/query/0x160b877451077c23c58163fe00af21e6d0d06bfc7da2cb82eaa432a409a10656, when the parachain host configuration was applied.

**Comment by sandreim** [comment]
Block times are also degraded, similarly to https://github.com/paritytech/polkadot-sdk/issues/8414

**Comment by pascuin** [comment]
Just to flag this here for the sake of completion, this has effects the block finalization on Acurast Canary.

**Comment by florentina57** [comment]
One of my Kusama validator nodes, running on 1.18.2 started initiating disputes on session 47735 and continues at 2025-05-09 18:57:01 (UTC) ```New dispute initiated for candidate.``` I am attaching some logs:

[validandina-lim.log.tgz](https://github.com/user-attachments/files/20127793/validandina-lim.log.tgz)

**Comment by tdimitrov** [comment]
`New dispute initiated for candidate.` only means that there is a dispute. It's not initiated by your node.

'Detected invalid candidate as an approval checker' or something related to 'invalid candidate' is an indication of a dispute triggered by the local node.

**Comment by tugytur** [comment]
We didn't have any `'invalid candidate` related logs. But here are the logs for the last 12 hours from our active Amforc validators

[validator1.tar.gz](https://github.com/user-attachments/files/20128566/validator1.tar.gz)
[validator2.tar.gz](https://github.com/user-attachments/files/20128571/validator2.tar.gz)
[validator3.tar.gz](https://github.com/user-attachments/files/20128570/validator3.tar.gz)
[validator4.tar.gz](https://github.com/user-attachments/files/20128572/validator4.tar.gz)
[validator5.tar.gz](https://github.com/user-attachments/files/20128569/validator5.tar.gz)
[validator6.tar.gz](https://github.com/user-attachments/files/20128567/validator6.tar.gz)
[validator7.tar.gz](https://github.com/user-attachments/files/20128568/validator7.tar.gz)

**Comment by florentina57** [comment]
> `New dispute initiated for candidate.` only means that there is a dispute. It's not initiated by your node.
> 
> 'Detected invalid candidate as an approval checker' or something related to 'invalid candidate' is an indication of a dispute triggered by the local node.

Thanks for clarifying that. My bad regarding the log message.

However, I actually noticed the dispute on [turboflakes](https://apps.turboflakes.io/). I saw that Paulo, from turboflakes, just posted a list 11 DN nodes, including mine, who have initiated disputes despite being on version 1.18.2

<img width="200" alt="Image" src="https://github.com/user-attachments/assets/6d1d588e-85e4-4140-8a41-a2a9338c7aa0" />

**Comment by paulormart** [comment]
@florentina57 could you share logs starting from ~17:00 UTC? The block number doesn't seem to be included in the logs you shared earlier.

<img width="764" alt="Image" src="https://github.com/user-attachments/assets/8490f8b3-18b1-4e06-95ba-57b92d101c68" />

**Comment by alexggh** [comment]
> However, I actually noticed the dispute on [turboflakes](https://apps.turboflakes.io/). I saw that Paulo, from turboflakes, just posted a list 11 DN nodes, including mine, who have initiated disputes despite being on version 1.18.2

If you look here https://apps.turboflakes.io/?chain=kusama#/insights?mode=history, between session 47732 and session 47734, you are going to see that we have disputes only from nodes that have v1.16 or lower, after that there seems to be some from 1.18.2, but at that point finality is already lagging hundreds of blocks, so it might be just a result of nodes being overloaded.

**Comment by florentina57** [comment]
> [@florentina57](https://github.com/florentina57) could you share logs starting from ~17:00 UTC? The block number doesn't seem to be included in the logs you shared earlier.
> 
> <img alt="Image" width="764" src="https://private-user-images.githubusercontent.com/4574742/442313064-8490f8b3-18b1-4e06-95ba-57b92d101c68.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDY4MjQyNjYsIm5iZiI6MTc0NjgyMzk2NiwicGF0aCI6Ii80NTc0NzQyLzQ0MjMxMzA2NC04NDkwZjhiMy0xOGIxLTRlMDYtOTViYS01N2I5MmQxMDFjNjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDUwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTA1MDlUMjA1MjQ2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MWExMTI5OGM0ZjBmMGVjZjQxNjlhNzM4NWJkMGRjNDBjNTMzMTY1NGFjNWEwZjBkZTc5NzcxN2Y2YmMxMmQxYiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.f8C_PaoAbz1TOwQrN625JHwMvqlHMKV8dOE92oHCBQs">

Thanks @paulormart I just tried getting those logs, but I have so many logs that the oldest I have as of now is 18:36 (UTC) so I guess I lost all logs prior to this time :/

**Comment by sandreim** [comment]
Quick update, a temporary fix is ready: https://github.com/paritytech/polkadot-sdk/pull/8483

**Comment by tugytur** [comment]
> Quick update, a temporary fix is ready: [#8483](https://github.com/paritytech/polkadot-sdk/pull/8483)

will this release come out tonight?

**Comment by sandreim** [comment]
We merged the fix.

The release will take a bit more time. In the mean time a binary with the fix can be built from the head of the stable2503 https://github.com/paritytech/polkadot-sdk/tree/stable2503

**Comment by lukeisontheroad** [comment]
Has this “fix” been applied?

**Comment by lukeisontheroad** [comment]
What’s the status now? It’s still not working. Please communicate.

**Comment by florentina57** [comment]
> We merged the fix.
> 
> The release will take a bit more time. In the mean time a binary with the fix can be built from the head of the stable2503 branch: https://github.com/paritytech/polkadot-sdk/tree/stable2503

I have compiled the binaries and upgraded both of my Kusama Validator Nodes. One of the two still saw some ```error=AuthorityFlooding``` after restarting the node but stabilized after 10-15 mins. Both nodes seem to have "normal" logs, aside from last finalized block that remains at #28282123.

**Comment by sandreim** [comment]
Emergency fix release is out: https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-stable2503-3

**Comment by kolkovsky** [comment]
Hello guys! 

I encountered an issue while using the Polkadot-JS API on Kusama. I detected a broken behavior for one method in the staking palette: claimedRewards.

<img width="1396" alt="Image" src="https://github.com/user-attachments/assets/11e169c8-45d7-4a14-98bb-3cf7e419f5ee" />

Before the incident with the network stability, I claimed rewards without any issues. The API returned a response that, while not ideal, was understandable. An empty array [] means no rewards were claimed in the era, and [0] means rewards were claimed in the era.

Currently, I am having trouble checking how many eras are available for validators to claim rewards.

For instance:
https://kusama.subscan.io/validator/DteShXKaQQy2un2VizKwwhViN5e7F47UrkAZDkxgK22LdBv?tab=era

The latest era when this validator earned points is 8056. If I input this data into [Polkadot-JS Apps](https://polkadot.js.org/apps/?rpc=wss://kusama.api.onfinality.io/public-ws#/chainstate) and try to call staking.claimedRewards(), I get the following response:

<img width="1380" alt="Image" src="https://github.com/user-attachments/assets/849f114f-ff17-42bc-85b4-4537ffe54ee3" />

Let’s check the same logic for unclaimed eras. For example, the next one 8057 also returns the same response:
[
  0
]

Some past eras show a new response, like 8051: [0, 1]. It’s unclear what this means for the validator.

I hope I’ve explained the issue clearly, and that you understand the problem that’s bothering me. If anyone has insights or ideas on how to resolve this, your input would be appreciated!

**Comment by burdges** [comment]
Can we tell if the disputing validators would consistently raise the same dispute?  Can we ask the operator to rerun the disputed parablock when refunding their slash?

**Comment by sandreim** [comment]
> Hello guys!
> 
> I encountered an issue while using the Polkadot-JS API on Kusama. I detected a broken behavior for one method in the staking palette: claimedRewards.

CC @paritytech/staking-core

**Comment by kianenigma** [comment]
@kolkovsky let's continue in https://github.com/polkadot-developers/polkadot-docs/issues/625, thanks!
