### ISSUE TITLE
range start index 150 out of range for slice of length 12

### ISSUE THREAD

**Issue by holitn-spec** [paritytech/polkadot-sdk#9169]
Version: 1.18.7-1530a882641

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
   7: core::slice::index::slice_start_index_len_fail
   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
   9: yamux::connection::Connection<T>::poll_next_inbound
  10: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
  11: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
  12: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::raw::poll
  14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  15: tokio::runtime::scheduler::multi_thread::worker::run
  16: tokio::runtime::task::raw::poll
  17: std::sys::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: std::sys::pal::unix::thread::Thread::new::thread_start
  20: start_thread
             at /build/glibc-FcRMwW/glibc-2.31/nptl/pthread_create.c:477:8
  21: clone
             at /build/glibc-FcRMwW/glibc-2.31/misc/../sysdeps/unix/sysv/linux/x86_64/clone.S:95

Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/yamux-0.13.5/src/frame/io.rs:96

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new

**Comment by bkchr** [comment]
CC @paritytech/networking

**Comment by lexnv** [comment]
Thanks for reporting @holitn-spec 🙏

Did the issue reproduce for you after restarting your node?
I expect this is a one-off issue since we have not seen it in Kusama for past half a year, but would like to gain more data on this

We are using the rust-yamux crate from upstream, I've submitted a fix at:
- https://github.com/libp2p/rust-yamux/pull/202

The fix aims at terminating the connection when the inner socket returns a written length that is larger than the internal header size (12 bytes).

**Comment by Anastasiia-Khab** [comment]
Same here in Polka and Kusama nodes

**Comment by lexnv** [comment]
@Anastasiia-Khab, how often do you see this happen? 

Could you enable `RUST_LOG='yamux=trace'` if this is reproducing on your side easily? Thanks 🙏

**Comment by lexnv** [comment]
The fix has been merged in the rust-yamux crate, pending a new release.

However, I would still like to understand how this happened (maybe that will lead to some other improvements). Atm, I couldn't reproduce this locally and my log files rapidly grew to 1.4 TB. 

If anyone is able to reproduce this please enable 🙏 
- `RUST_LOG=yamux=trace,litep2p::websocket=trace,litep2p::transport::websocket::stream=trace,litep2p::substream=trace`

**Comment by lexnv** [comment]
@Anastasiia-Khab does the stack trace look identical in your case? Most importantly, is the connection that caused the panic using the websocket transport?

**Comment by m-saxemberg** [comment]
Today we want to inform that the same issue persists in the [1.19.0 release](https://github.com/paritytech/polkadot-sdk/releases/tag/polkadot-stable2506)

This error was found on one of our RPC machines that provide relaychain (Polkadot) information to other nodes.

====================

Version: 1.19.0-6fd693e6d9c

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
   7: core::slice::index::slice_start_index_len_fail
   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
   9: yamux::connection::Connection<T>::poll_next_inbound
  10: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
  11: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
  12: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  13: tokio::runtime::task::raw::poll
  14: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  15: tokio::runtime::scheduler::multi_thread::worker::run
  16: tokio::runtime::task::raw::poll
  17: std::sys::backtrace::__rust_begin_short_backtrace
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: std::sys::pal::unix::thread::Thread::new::thread_start
  20: <unknown>
  21: <unknown>


Thread 'tokio-runtime-worker' panicked at 'range start index 147 out of range for slice of length 12', /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/yamux-0.13.5/src/frame/io.rs:96

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new

Since this is a non-validator machine we will proceed to start the node with the following instructions 

`RUST_LOG=yamux=trace,litep2p::websocket=trace,litep2p::transport::websocket::stream=trace,litep2p::substream=trace`

requested here: https://github.com/paritytech/polkadot-sdk/issues/9269#issuecomment-3096164370 

We will report back in case we find anything on this node with the mentioned log flags.

**Comment by m-saxemberg** [comment]
the following is the output for a RPC node that caught this error with the suggested log flags
RUST_LOG=yamux=trace,litep2p::websocket=trace,litep2p::transport::websocket::stream=trace,litep2p::substream=trace
running Version: 1.19.0-6fd693e6d9c
https://gist.github.com/m-saxemberg/6cbd5d76267cb3b8b970a892bc6c110b
@lexnv

**Comment by m-saxemberg** [comment]
A bigger log file of the issue since the other had probably not enough lines, for the same RPC node using
RUST_LOG=yamux=trace,litep2p::websocket=trace,litep2p::transport::websocket::stream=trace,litep2p::substream=trace
running Version: 1.19.0-6fd693e6d9c

https://gist.github.com/m-saxemberg/093145cec5429feb8314617ebdf32201

Let us know if you guys need more lines of logs

**Comment by lexnv** [comment]
Thanks! This helps, will have a look at this tomorrow 🙏

**Comment by m-saxemberg** [comment]
FYI
The same issue appeared again on Version: 1.19.1-f3969c7ddd3

====================

Version: 1.19.1-f3969c7ddd3

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: __rustc::rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
   7: core::slice::index::slice_start_index_len_fail
   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
   9: yamux::connection::Connection<T>::poll_next_inbound
  10: litep2p::yamux::control::ControlledConnection<T>::poll_next
  11: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  12: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
  13: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::core::Core<T,S>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run
  21: tokio::runtime::context::scoped::Scoped<T>::set
  22: tokio::runtime::context::runtime::enter_runtime
  23: tokio::runtime::scheduler::multi_thread::worker::run
  24: tokio::runtime::task::core::Core<T,S>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: std::sys::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: std::sys::pal::unix::thread::Thread::new::thread_start
  30: <unknown>
  31: <unknown>


Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /home/near_user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.5/src/frame/io.rs:96

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new

**Comment by m-saxemberg** [comment]
Issue present again in:

Version: 1.19.2-2caeef482a4

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
   2: std::panicking::begin_panic_handler::{{closure}}
   3: std::sys::backtrace::__rust_end_short_backtrace
   4: __rustc::rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
   7: core::slice::index::slice_start_index_len_fail
   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
   9: yamux::connection::Connection<T>::poll_next_inbound
  10: litep2p::yamux::control::ControlledConnection<T>::poll_next
  11: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  12: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
  13: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::core::Core<T,S>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run
  21: tokio::runtime::context::scoped::Scoped<T>::set
  22: tokio::runtime::context::runtime::enter_runtime
  23: tokio::runtime::scheduler::multi_thread::worker::run
  24: tokio::runtime::task::core::Core<T,S>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: std::sys::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: std::sys::pal::unix::thread::Thread::new::thread_start
  30: <unknown>
  31: <unknown>


Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /home/near_user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.5/src/frame/io.rs:96

This is a bug. Please report it at:

**Comment by lexnv** [comment]
We are currently blocked from backporting the fix to older polkadot versions:
- https://github.com/paritytech/polkadot-sdk/pull/9485

The issue stems from the usage of rust-yamux usage of unstable rust features:
- https://github.com/paritytech/polkadot-sdk/actions/runs/17407046512/job/49414334808

```
 error[E0658]: use of unstable library feature `unsigned_is_multiple_of`
   --> /usr/local/cargo/registry/src/index.crates.io-6f17d22bba15001f/yamux-0.13.6/src/frame/header.rs:301:16
    |
301 |         self.0.is_multiple_of(2)
    |                ^^^^^^^^^^^^^^
    |
    = note: see issue #128101 <https://github.com/rust-lang/rust/issues/128101> for more information
```

This feature has been stabilized for 1.88. However, our older releases are still running with 1.85. The backporting effort of 1.88 to older releases has been considered in the past, but it is not as straight forward:
- https://github.com/paritytech/polkadot-sdk/pull/9229


It is not entirely clear why `self.0 % 2` was not adopted for rust-yamux. I'll try to discuss this further with the Rust-yamux maintainers to determine the best course of action, as this crate is outside of our control.

**Comment by bkchr** [comment]
> This feature has been stabilized for 1.88. However, our older releases are still running with 1.85. The backporting effort of 1.88 to older releases has been considered in the past, but it is not as straight forward:

I have high doubts that we need this linked pr to use `1.88` to build older releases. None of the changes is breaking and all should just be warnings (which can be ignored). So, I don't really see how this is blocked on this. Yeah, yamux should not have done this, but I have doubts that it is easier to get them to change their stuff than us to just use 1.88.

**Comment by m-saxemberg** [comment]
Issue present on Version: 1.19.2-2caeef482a4   
now on a live validator

```
2025-09-24 🏆 Imported #27907796 (0x8e7e…6ed9 → 0xd736…e3d0)                          
2025-09-24 maintain txs=(1, 0) a=1 i=4 views=[(27907796, 0, 0)] event=NewBestBlock { hash: 0xd736ec967b5efacc919c892878583aa082fd21f227488d5ba7f212805dc1e3d0, tree_route: None } duration=2.445621ms                                                                                                                                                                              
2025-09-24  💤 Idle (40 peers), best: #27907796 (0xd736…e3d0), finalized #27907792 (0x98d0…4a82), ⬇ 2.5MiB/s ⬆ 3.3MiB/s                                                                                                              
====================                                                                                                                                                                                                                                                                                                                                                                        
Version: 1.19.2-2caeef482a4                                                                                                                                                                                                                  
   0: sp_panic_handler::set::{{closure}}                                                                                                                                                         1: std::panicking::rust_panic_with_hook                                                                                                                                                    
   2: std::panicking::begin_panic_handler::{{closure}}                                                                                                                                           3: std::sys::backtrace::__rust_end_short_backtrace                                                                                                                                         
   4: __rustc::rust_begin_unwind                                                                                                                                                                 5: core::panicking::panic_fmt               
   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime                                                                                                                          7: core::slice::index::slice_start_index_len_fail                                                                                                                                          
   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready                                                                                                       9: yamux::connection::Connection<T>::poll_next_inbound                                                                                                                                     
  10: litep2p::yamux::control::ControlledConnection<T>::poll_next                                                                                                                               11: <core::future::poll_fn::PollFn<F> as core::future::future::Future>::poll                 
  12: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}                                                                                                      
  13: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: tokio::runtime::task::core::Core<T,S>::poll
  18: tokio::runtime::task::harness::Harness<T,S>::poll
  19: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run
  21: tokio::runtime::context::scoped::Scoped<T>::set
  22: tokio::runtime::context::runtime::enter_runtime
  23: tokio::runtime::scheduler::multi_thread::worker::run
  24: tokio::runtime::task::core::Core<T,S>::poll
  25: tokio::runtime::task::harness::Harness<T,S>::poll
  26: tokio::runtime::blocking::pool::Inner::run
  27: std::sys::backtrace::__rust_begin_short_backtrace
  28: core::ops::function::FnOnce::call_once{{vtable.shim}}
  29: std::sys::pal::unix::thread::Thread::new::thread_start
  30: <unknown>
  31: <unknown>


Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /home/polkadot_user/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.5/src/frame/io.rs:96

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot-sdk/issues/new

2025-09-24  WARN parachain::pvf-common: worker: error occurred: An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109164, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24 WARN parachain::pvf-common: worker: error occurred sending result to host: Broken pipe (os error 32) worker_info=WorkerInfo { pid: 1109164, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: quitting pvf worker (execute): An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109164, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: quitting pvf worker (prepare): failed to fill whole buffer worker_info=WorkerInfo { pid: 1109556, kind: Prepare, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred: An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1131469, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred sending result to host: Broken pipe (os error 32) worker_info=WorkerInfo { pid: 1131469, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: quitting pvf worker (execute): An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1131469, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred: An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109196, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred sending result to host: Broken pipe (os error 32) worker_info=WorkerInfo { pid: 1109196, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: quitting pvf worker (execute): An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109196, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred: An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109197, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: worker: error occurred sending result to host: Broken pipe (os error 32) worker_info=WorkerInfo { pid: 1109197, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
2025-09-24  WARN parachain::pvf-common: quitting pvf worker (execute): An internal error occurred: validation: some communication error occurred with the host: failed to fill whole buffer worker_info=WorkerInfo { pid: 1109197, kind: Execute, version: Some("1.19.2"), worker_dir_path: "/" }
```

**Comment by LukeWheeldon** [comment]
`$ polkadot --version
polkadot 1.20.0-5ab401310d2`
```
Oct 14 02:10:24 node-es polkadot[482990]: ====================
Oct 14 02:10:24 node-es polkadot[482990]: Version: 1.20.0-5ab401310d2
Oct 14 02:10:24 node-es polkadot[482990]:    0: sp_panic_handler::set::{{closure}}
Oct 14 02:10:24 node-es polkadot[482990]:    1: std::panicking::rust_panic_with_hook
Oct 14 02:10:24 node-es polkadot[482990]:    2: std::panicking::begin_panic_handler::{{closure}}
Oct 14 02:10:24 node-es polkadot[482990]:    3: std::sys::backtrace::__rust_end_short_backtrace
Oct 14 02:10:24 node-es polkadot[482990]:    4: __rustc::rust_begin_unwind
Oct 14 02:10:24 node-es polkadot[482990]:    5: core::panicking::panic_fmt
Oct 14 02:10:24 node-es polkadot[482990]:    6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
Oct 14 02:10:24 node-es polkadot[482990]:    7: core::slice::index::slice_start_index_len_fail
Oct 14 02:10:24 node-es polkadot[482990]:    8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
Oct 14 02:10:24 node-es polkadot[482990]:    9: yamux::connection::Connection<T>::poll_next_inbound
Oct 14 02:10:24 node-es polkadot[482990]:   10: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
Oct 14 02:10:24 node-es polkadot[482990]:   11: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
Oct 14 02:10:24 node-es polkadot[482990]:   12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
Oct 14 02:10:24 node-es polkadot[482990]:   13: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Oct 14 02:10:24 node-es polkadot[482990]:   14: tokio::runtime::task::raw::poll
Oct 14 02:10:24 node-es polkadot[482990]:   15: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
Oct 14 02:10:24 node-es polkadot[482990]:   16: tokio::runtime::scheduler::multi_thread::worker::run
Oct 14 02:10:24 node-es polkadot[482990]:   17: tokio::runtime::task::raw::poll
Oct 14 02:10:24 node-es polkadot[482990]:   18: std::sys::backtrace::__rust_begin_short_backtrace
Oct 14 02:10:24 node-es polkadot[482990]:   19: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct 14 02:10:24 node-es polkadot[482990]:   20: std::sys::pal::unix::thread::Thread::new::thread_start
Oct 14 02:10:24 node-es polkadot[482990]:   21: <unknown>
Oct 14 02:10:24 node-es polkadot[482990]:   22: <unknown>
Oct 14 02:10:24 node-es polkadot[482990]: Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.6/src/frame/io.rs:96
Oct 14 02:10:24 node-es polkadot[482990]: This is a bug. Please report it at:
Oct 14 02:10:24 node-es polkadot[482990]:         https://github.com/paritytech/polkadot-sdk/issues/new
Oct 14 02:10:24 node-es systemd[1]: kusama-validator.service: Main process exited, code=exited, status=1/FAILURE
Oct 14 02:10:24 node-es systemd[1]: kusama-validator.service: Failed with result 'exit-code'.
O
```

**Comment by lexnv** [comment]
Rust yamux team fixed the compilation for older versions. I've published a new fix for litep2p to ensure we are not re-polling the broken component. This will land soon in a new litep2p release:
- https://github.com/paritytech/litep2p/pull/445

**Comment by m-saxemberg** [comment]
> Rust yamux team fixed the compilation for older versions. I've published a new fix for litep2p to ensure we are not re-polling the broken component. This will land soon in a new litep2p release:
> 
> * [yamux/control: Ensure poll next inbound is not called after errors litep2p#445](https://github.com/paritytech/litep2p/pull/445)

We recently had the exact same issue as [LukeWheeldon](https://github.com/LukeWheeldon)
What is the recommended way to avoid it? Just to wait for the next litep2p release?

**Comment by lexnv** [comment]
While investigating this, I discovered that the issue could also arise from yamux calling `poll_ready` from a poisoned/broken state:
- https://github.com/libp2p/rust-yamux/pull/211

The best course of action would be waiting for the next polakdot release which should include these fixes as well 🙏

**Comment by RomarQ** [comment]
@lexnv at moonbeam, just last week, 3 new issues have been created about this panic:

- https://github.com/moonbeam-foundation/moonbeam/issues/3504
- https://github.com/moonbeam-foundation/moonbeam/issues/3506
- https://github.com/moonbeam-foundation/moonbeam/issues/3509

Updating `yamux` to `0.13.8` and `litep2p` to `0.11.0` everywhere should be enough to address these issues, right?

**Comment by lexnv** [comment]
Hey @RomarQ, we'll need to bake a new litep2p release including the following as well:
- github.com/paritytech/litep2p/pull/445

**Comment by RomarQ** [comment]
Do you think it would be possible to have a new release later today or tomorrow? 

We wanted to include it in the next client release on Wednesday

**Comment by lexnv** [comment]
Sure thing, we'll tackle this tomorrow since there's one other feature we'd like to include in the upcoming release 🙏 

> We wanted to include it in the next client release on Wednesday

That would be helpful since the issue is not reproducing in our environment (only with patched rust-yamux that panics on purpose). This would help us validate the fix as well, thanks

**Comment by RomarQ** [comment]
> Sure thing, we'll tackle this tomorrow since there's one other feature we'd like to include in the upcoming release 🙏
> 
> > We wanted to include it in the next client release on Wednesday
> 
> That would be helpful since the issue is not reproducing in our environment (only with patched rust-yamux that panics on purpose). This would help us validate the fix as well, thanks

Hi @lexnv,

Can you provide any ETA for when the new litep2p release will be out?

**Comment by lexnv** [comment]
Hey, we should have it pulled into polkadot in a few hours once we merge:
- https://github.com/paritytech/litep2p/pull/461

**Comment by lexnv** [comment]
@RomarQ https://crates.io/crates/litep2p litep2p 0.11.1 has been released. Feel free to include it as `cargo update litep2p` for the moonbeam release 🙏 Would love to hear back from you if this solves the issue thanks!

**Comment by RomarQ** [comment]
> [@RomarQ](https://github.com/RomarQ) https://crates.io/crates/litep2p litep2p 0.11.1 has been released. Feel free to include it as `cargo update litep2p` for the moonbeam release 🙏 Would love to hear back from you if this solves the issue thanks!

Thanks @lexnv

The new client will be released tomorrow. Will let you if we receive any new report on the upcoming version.

**Comment by lexnv** [comment]
@RomarQ did the litep2p update solve the issue for you at Moonbeam? 🙏

**Comment by RomarQ** [comment]
> [@RomarQ](https://github.com/RomarQ) did the litep2p update solve the issue for you at Moonbeam? 🙏

I think it did, no more reports about this issue

**Comment by lexnv** [comment]
Perfect! I'll bring the update to Polkadot shortly, thanks for double-checking this 🙏

**Comment by vino-hank** [comment]
The panic error still exists:

`first panic`
--
7490-2025-11-19 02:45:48 maintain txs=(0, 0) a=2 i=4 views=[(28698196, 0, 0), (28698196, 0, 0)] event=NewBestBlock { hash: 0xf5c224c192a478cc3be30f98ab80c3e52d5454ebd790c39a878916db82e54f35, tree_route: Some(TreeRoute { route: [HashAndNumber { number: 28698196, hash: 0x46a485fcea9b9a941983a03682fa20c9c4d09b2706f0d3ff40883ff8ac068584 }, HashAndNumber { number: 28698195, hash: 0x7b1efbb7ec8be0ea61cd6e9f2ebdfb6b64f5aa62853062de3f048901a88d3519 }], pivot: 1 }) } duration=3.187847ms
7491-2025-11-19 02:45:49 maintain txs=(0, 0) a=2 i=3 views=[(28698196, 0, 0), (28698196, 0, 0)] event=Finalized { hash: 0x7b5ad7755d23e07464d80e57ece7e5e3920998d969b5300dbb280716ffa544bd, tree_route: [] } duration=455.002µs
7492-2025-11-19 02:45:51 💤 Idle (18 peers), best: #28698196 (0xf5c2…4f35), finalized #28698193 (0x7b5a…44bd), ⬇ 554.4kiB/s ⬆ 302.2kiB/s
7493-
7494-====================
7495-
7496-Version: 1.20.2-7304752b478
7497-
7498-   0: sp_panic_handler::set::{{closure}}
7499-   1: std::panicking::rust_panic_with_hook
7500-   2: std::panicking::begin_panic_handler::{{closure}}
7501-   3: std::sys::backtrace::__rust_end_short_backtrace
7502-   4: __rustc::rust_begin_unwind
7503-   5: core::panicking::panic_fmt
7504-   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
7505-   7: core::slice::index::slice_start_index_len_fail
7506-   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
7507-   9: yamux::connection::Connection<T>::poll_next_inbound
7508-  10: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
7509-  11: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
7510-  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
7511-  13: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
7512-  14: tokio::runtime::task::raw::poll
7513-  15: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
7514-  16: tokio::runtime::scheduler::multi_thread::worker::run
7515-  17: tokio::runtime::task::raw::poll
7516-  18: std::sys::backtrace::__rust_begin_short_backtrace
7517-  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
7518-  20: std::sys::pal::unix::thread::Thread::new::thread_start
7519-  21: start_thread
7520-  22: clone
7521-
7522-
7523-Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.6/src/frame/io.rs:96
7524-
7525-This is a bug. Please report it at:
7526-
7527-	https://github.com/paritytech/polkadot-sdk/issues/new
7528-
7529-2025-11-19 02:45:53 Parity Polkadot
7530-2025-11-19 02:45:53 ✌️  version 1.20.2-7304752b478 

`second panic`
--
22463-2025-11-19 08:19:20 🏆 Imported #28701501 (0x0f24…06c3 → 0x7ff9…b778)
22464-2025-11-19 08:19:20 maintain txs=(0, 0) a=1 i=4 views=[(28701501, 0, 0)] event=NewBestBlock { hash: 0x7ff98169feac0c0ca10c1fa3874613840942ee8717613263b50c02aa176ab778, tree_route: None } duration=607.333µs
22465-2025-11-19 08:19:21 💤 Idle (17 peers), best: #28701501 (0x7ff9…b778), finalized #28701497 (0xebf2…5d66), ⬇ 573.2kiB/s ⬆ 360.8kiB/s
22466-
22467-====================
22468-
22469-Version: 1.20.2-7304752b478
22470-
22471-   0: sp_panic_handler::set::{{closure}}
22472-   1: std::panicking::rust_panic_with_hook
22473-   2: std::panicking::begin_panic_handler::{{closure}}
22474-   3: std::sys::backtrace::__rust_end_short_backtrace
22475-   4: __rustc::rust_begin_unwind
22476-   5: core::panicking::panic_fmt
22477-   6: core::slice::index::slice_start_index_len_fail::do_panic::runtime
22478-   7: core::slice::index::slice_start_index_len_fail
22479-   8: <yamux::frame::io::Io<T> as futures_sink::Sink<yamux::frame::Frame<()>>>::poll_ready
22480-   9: yamux::connection::Connection<T>::poll_next_inbound
22481-  10: litep2p::transport::websocket::connection::WebSocketConnection::start::{{closure}}
22482-  11: <litep2p::transport::websocket::WebSocketTransport as litep2p::transport::Transport>::accept::{{closure}}
22483-  12: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
22484-  13: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
22485-  14: tokio::runtime::task::raw::poll
22486-  15: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
22487-  16: tokio::runtime::scheduler::multi_thread::worker::run
22488-  17: tokio::runtime::task::raw::poll
22489-  18: std::sys::backtrace::__rust_begin_short_backtrace
22490-  19: core::ops::function::FnOnce::call_once{{vtable.shim}}
22491-  20: std::sys::pal::unix::thread::Thread::new::thread_start
22492-  21: start_thread
22493-  22: clone
22494-
22495-
22496-Thread 'tokio-runtime-worker' panicked at 'range start index 150 out of range for slice of length 12', /usr/local/cargo/registry/src/index.crates.io-1949cf8c6b5b557f/yamux-0.13.6/src/frame/io.rs:96
22497-
22498-This is a bug. Please report it at:
22499-
22500-	https://github.com/paritytech/polkadot-sdk/issues/new
22501-
22502-2025-11-19 08:19:22 Parity Polkadot

**Comment by bkchr** [comment]
@lexnv any update?

**Comment by lexnv** [comment]
Sorry for the annoyance here, the yamux fix was included in the latest 2512 release:

 https://github.com/paritytech/polkadot-sdk/blob/a58c2ddf09c535f35f7cd1b09f059d1024fec986/Cargo.lock#L9891

However, older releases did not receive it, similar to @vino-hank which runs on 2509. To close the gap on older releases I've opened: 
- https://github.com/paritytech/polkadot-sdk/pull/10479


@vino-hank Could you please confirm as well that running from latest 2512 release mitigates the issue for you? 🙏

**Comment by vino-hank** [comment]
stable2512 works for me. thank you! @lexnv

**Comment by bkchr** [comment]
Ty for confirming @vino-hank. Closing the issue, 2512 contains the fix.
